server:
#  port: 8081
  port: 0

spring:
  application:
    name: ptm-c-k
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:
      bindings:
        processOrder-in-0:
          destination: ptm-kinesis-stream
          content-type: application/json
          group: g100
    function:
      definition: processOrder
